"""primeiro_acesso em usuario

Revision ID: 91a2ecf56a41
Revises: f958d38a7f19
Create Date: 2026-06-15 20:23:36.777764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a2ecf56a41'
down_revision = 'f958d38a7f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primeiro_acesso', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('primeiro_acesso')

    # ### end Alembic commands ###
