"""periodo_base em indicador_analise

Revision ID: c7189696a9cd
Revises: d87a6fbc2fbe
Create Date: 2026-06-15 00:58:40.197084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7189696a9cd'
down_revision = 'd87a6fbc2fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicador_analise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo_base_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('periodo_base_fim', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicador_analise', schema=None) as batch_op:
        batch_op.drop_column('periodo_base_fim')
        batch_op.drop_column('periodo_base_inicio')

    # ### end Alembic commands ###
