"""guia_topico (CMS base de conhecimento)

Revision ID: d61b5e68082c
Revises: 91a2ecf56a41
Create Date: 2026-06-15 21:32:48.964156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61b5e68082c'
down_revision = '91a2ecf56a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guia_topico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('pergunta', sa.String(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guia_topico', schema=None) as batch_op:
        batch_op.create_index('ix_guia_topico_categoria', ['categoria'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guia_topico', schema=None) as batch_op:
        batch_op.drop_index('ix_guia_topico_categoria')

    op.drop_table('guia_topico')
    # ### end Alembic commands ###
