"""schema inicial nexo (sqlite para supabase postgres)

Revision ID: d87a6fbc2fbe
Revises: 
Create Date: 2026-06-11 22:47:03.824673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87a6fbc2fbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plano',
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_mensal', sa.Numeric(), nullable=False),
    sa.Column('qtd_analises_mes', sa.Integer(), nullable=False),
    sa.Column('tipo_analise_permitida', sa.String(), nullable=False),
    sa.Column('nivel_entrega_analise', sa.String(), nullable=False),
    sa.Column('nivel_dashboard', sa.String(), nullable=False),
    sa.Column('nivel_atendimento', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.CheckConstraint("nivel_atendimento IN ('BAIXO', 'MEDIO', 'ALTO')"),
    sa.CheckConstraint("nivel_dashboard IN ('RESUMIDO', 'GERENCIAL', 'COMPLETO')"),
    sa.CheckConstraint("nivel_entrega_analise IN ('BASICA', 'COMPLETA', 'PREMIUM')"),
    sa.CheckConstraint("nome_plano IN ('BRONZE', 'PRATA', 'OURO')"),
    sa.CheckConstraint("tipo_analise_permitida IN ('MENSAL', 'QUINZENAL')"),
    sa.PrimaryKeyConstraint('id_plano'),
    sa.UniqueConstraint('nome_plano')
    )
    op.create_table('segmento',
    sa.Column('id_segmento', sa.Integer(), nullable=False),
    sa.Column('nome_segmento', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_segmento'),
    sa.UniqueConstraint('nome_segmento')
    )
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_segmento', sa.Integer(), nullable=False),
    sa.Column('id_plano_atual', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('email_contato', sa.String(), nullable=False),
    sa.Column('telefone_contato', sa.String(), nullable=True),
    sa.Column('data_contratacao', sa.Date(), nullable=False),
    sa.Column('faturamento_base_mensal', sa.Numeric(), nullable=True),
    sa.Column('status_conta', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status_conta IN ('ATIVA', 'SUSPENSA', 'CANCELADA')"),
    sa.ForeignKeyConstraint(['id_plano_atual'], ['plano.id_plano'], ),
    sa.ForeignKeyConstraint(['id_segmento'], ['segmento.id_segmento'], ),
    sa.PrimaryKeyConstraint('id_empresa'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(role = 'CLIENTE' AND id_empresa IS NOT NULL) OR (role = 'ADMIN'   AND id_empresa IS NULL)", name='ck_usuario_role_empresa'),
    sa.CheckConstraint("role IN ('ADMIN', 'CLIENTE')"),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analise',
    sa.Column('id_analise', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_plano_referencia', sa.Integer(), nullable=False),
    sa.Column('id_usuario_admin_responsavel', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fim', sa.Date(), nullable=False),
    sa.Column('mes_referencia', sa.Integer(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('tipo_analise', sa.String(), nullable=False),
    sa.Column('quinzena_referencia', sa.Integer(), nullable=True),
    sa.Column('status_analise', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(tipo_analise = 'MENSAL'    AND quinzena_referencia IS NULL) OR (tipo_analise = 'QUINZENAL' AND quinzena_referencia IS NOT NULL                             AND quinzena_referencia IN (1, 2))", name='ck_analise_tipo_quinzena'),
    sa.CheckConstraint("status_analise IN ('AGUARDANDO_RELATORIO', 'RELATORIO_RECEBIDO', 'EM_ANALISE', 'CONCLUIDO')"),
    sa.CheckConstraint("tipo_analise IN ('MENSAL', 'QUINZENAL')"),
    sa.CheckConstraint('mes_referencia BETWEEN 1 AND 12'),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_plano_referencia'], ['plano.id_plano'], ),
    sa.ForeignKeyConstraint(['id_usuario_admin_responsavel'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_analise')
    )
    op.create_table('chamado_suporte',
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('id_usuario_cliente', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('status_chamado', sa.String(), nullable=False),
    sa.Column('prioridade', sa.String(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.CheckConstraint("categoria IN ('FINANCEIRO', 'DUVIDA_TECNICA', 'ERRO_INTEGRACAO')"),
    sa.CheckConstraint("prioridade IN ('BAIXA', 'MEDIA', 'ALTA')"),
    sa.CheckConstraint("status_chamado IN ('ABERTO', 'EM_ATENDIMENTO', 'RESOLVIDO')"),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id_empresa'], ),
    sa.ForeignKeyConstraint(['id_usuario_cliente'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_chamado')
    )
    with op.batch_alter_table('chamado_suporte', schema=None) as batch_op:
        batch_op.create_index('ix_chamado_empresa', ['id_empresa'], unique=False)

    op.create_table('notificacao',
    sa.Column('id_notificacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('link_destino', sa.String(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacao')
    )
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.create_index('ix_notificacao_usuario', ['id_usuario'], unique=False)

    op.create_table('indicador_analise',
    sa.Column('id_indicador', sa.Integer(), nullable=False),
    sa.Column('id_analise', sa.Integer(), nullable=False),
    sa.Column('faturamento_total', sa.Numeric(), nullable=True),
    sa.Column('total_comprado', sa.Numeric(), nullable=True),
    sa.Column('saldo_estimado_compras_vendas', sa.Numeric(), nullable=True),
    sa.Column('produto_mais_vendido_nome', sa.String(), nullable=True),
    sa.Column('produto_mais_vendido_quantidade', sa.Numeric(), nullable=True),
    sa.Column('produto_maior_faturamento_nome', sa.String(), nullable=True),
    sa.Column('produto_maior_faturamento_valor', sa.Numeric(), nullable=True),
    sa.Column('produto_maior_saldo_parado_nome', sa.String(), nullable=True),
    sa.Column('saldo_estimado_parado', sa.Numeric(), nullable=True),
    sa.Column('versao_processamento', sa.Integer(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_analise'], ['analise.id_analise'], ),
    sa.PrimaryKeyConstraint('id_indicador'),
    sa.UniqueConstraint('id_analise')
    )
    op.create_table('mensagem_suporte',
    sa.Column('id_mensagem', sa.Integer(), nullable=False),
    sa.Column('id_chamado', sa.Integer(), nullable=False),
    sa.Column('id_usuario_remetente', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_chamado'], ['chamado_suporte.id_chamado'], ),
    sa.ForeignKeyConstraint(['id_usuario_remetente'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    with op.batch_alter_table('mensagem_suporte', schema=None) as batch_op:
        batch_op.create_index('ix_mensagem_chamado', ['id_chamado'], unique=False)

    op.create_table('produto_curva_abc',
    sa.Column('id_produto_abc', sa.Integer(), nullable=False),
    sa.Column('id_analise', sa.Integer(), nullable=False),
    sa.Column('posicao_ranking', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(), nullable=False),
    sa.Column('faturamento', sa.Numeric(), nullable=False),
    sa.Column('quantidade', sa.Numeric(), nullable=True),
    sa.Column('percentual_individual', sa.Numeric(), nullable=False),
    sa.Column('percentual_acumulado', sa.Numeric(), nullable=False),
    sa.Column('classe_abc', sa.String(), nullable=False),
    sa.Column('data_geracao', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("classe_abc IN ('A', 'B', 'C')"),
    sa.ForeignKeyConstraint(['id_analise'], ['analise.id_analise'], ),
    sa.PrimaryKeyConstraint('id_produto_abc'),
    sa.UniqueConstraint('id_analise', 'posicao_ranking', name='uq_abc_analise_posicao')
    )
    with op.batch_alter_table('produto_curva_abc', schema=None) as batch_op:
        batch_op.create_index('ix_abc_analise', ['id_analise'], unique=False)

    op.create_table('relatorio_analise',
    sa.Column('id_relatorio', sa.Integer(), nullable=False),
    sa.Column('id_analise', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('resumo_executivo', sa.Text(), nullable=True),
    sa.Column('pontos_positivos', sa.Text(), nullable=True),
    sa.Column('pontos_de_alerta', sa.Text(), nullable=True),
    sa.Column('recomendacoes', sa.Text(), nullable=True),
    sa.Column('conclusao_estrategica', sa.Text(), nullable=False),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_analise'], ['analise.id_analise'], ),
    sa.PrimaryKeyConstraint('id_relatorio'),
    sa.UniqueConstraint('id_analise')
    )
    op.create_table('upload_relatorio',
    sa.Column('id_upload', sa.Integer(), nullable=False),
    sa.Column('id_analise', sa.Integer(), nullable=False),
    sa.Column('id_usuario_admin', sa.Integer(), nullable=True),
    sa.Column('tipo_relatorio', sa.String(), nullable=False),
    sa.Column('nome_arquivo_original', sa.String(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(), nullable=False),
    sa.Column('extensao_arquivo', sa.String(), nullable=False),
    sa.Column('tamanho_arquivo', sa.Integer(), nullable=True),
    sa.Column('hash_arquivo', sa.String(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status_processamento', sa.String(), nullable=False),
    sa.Column('data_processamento', sa.DateTime(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.CheckConstraint("extensao_arquivo IN ('CSV', 'XLSX', 'XLS')"),
    sa.CheckConstraint("status_processamento IN ('PENDENTE', 'PROCESSADO', 'ERRO')"),
    sa.CheckConstraint("tipo_relatorio IN ('VENDAS', 'COMPRAS')"),
    sa.ForeignKeyConstraint(['id_analise'], ['analise.id_analise'], ),
    sa.ForeignKeyConstraint(['id_usuario_admin'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_upload'),
    sa.UniqueConstraint('id_analise', 'tipo_relatorio', name='uq_upload_analise_tipo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_relatorio')
    op.drop_table('relatorio_analise')
    with op.batch_alter_table('produto_curva_abc', schema=None) as batch_op:
        batch_op.drop_index('ix_abc_analise')

    op.drop_table('produto_curva_abc')
    with op.batch_alter_table('mensagem_suporte', schema=None) as batch_op:
        batch_op.drop_index('ix_mensagem_chamado')

    op.drop_table('mensagem_suporte')
    op.drop_table('indicador_analise')
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.drop_index('ix_notificacao_usuario')

    op.drop_table('notificacao')
    with op.batch_alter_table('chamado_suporte', schema=None) as batch_op:
        batch_op.drop_index('ix_chamado_empresa')

    op.drop_table('chamado_suporte')
    op.drop_table('analise')
    op.drop_table('usuario')
    op.drop_table('empresa')
    op.drop_table('segmento')
    op.drop_table('plano')
    # ### end Alembic commands ###
