"""gerado_por_ia em relatorio_analise

Revision ID: f958d38a7f19
Revises: c7189696a9cd
Create Date: 2026-06-15 03:07:48.902575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f958d38a7f19'
down_revision = 'c7189696a9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_analise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gerado_por_ia', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_analise', schema=None) as batch_op:
        batch_op.drop_column('gerado_por_ia')

    # ### end Alembic commands ###
